version: "3"
services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  web:
    build: .
    volumes:
      - .:/develop
    depends_on:
      - db
    ports:
      - 4000:4000
    command: "mix phx.server"
